# These inputs are independent of the implementation. Expected output is captured
# from the accepted extraction parent, never regenerated by normal tests.
using Random
bits(x::AbstractArray{Float64}) = [string(reinterpret(UInt64,v); base=16,pad=16) for v in vec(x)]
bits(x::Float64) = string(reinterpret(UInt64,x); base=16,pad=16)
function serial_record(api, mode)
    init=MersenneTwister(592)
    state=api.SwarmState(rand(init,3,5).*2 .- 1, randn(init,3,5).*0.4)
    lower=[-1.3,-1.7,-1.1];upper=[1.8,1.2,1.9]
    visits=Float64[];culls=Int[]
    evaluate=(x;cost_cutoff=Inf)->begin
        append!(visits,x)
        (total=sum(abs2,x)+0.137*x[1]*x[2]+0.29*x[3],)
    end
    cull! = (s,i,rng)->begin
        push!(culls,i)
        if mode=="culling" && i==2
            s.positions[:,5].=rand(rng,3).*0.4
            s.velocities[:,5].=0
            s.pbest[:,5].=s.positions[:,5]
            s.pbest_cost[5]=Inf
            return 1
        end
        0
    end
    policy=api.SearchPolicy(evaluate=evaluate,
        weights=i->(w_inertia=0.67-0.013*i,c1=1.23+0.071*i,c2=2.07-0.023*i),
        cull! = cull!,feasible=c->c!==nothing,materially_better=(a,b)->a<b-0.05)
    settings=api.SearchSettings(6,mode=="stopping",1,0,0.23)
    rng=MersenneTwister(401)
    api._search!(state,lower,upper,settings,policy;rng)
    Dict("positions"=>bits(state.positions),"velocities"=>bits(state.velocities),
        "pbest"=>bits(state.pbest),"pbest_cost"=>bits(state.pbest_cost),
        "gbest"=>bits(state.gbest),"gbest_cost"=>bits(state.gbest_cost),
        "cost_history"=>bits(state.cost_history),"evaluation_order"=>bits(visits),
        "culling_iterations"=>culls,"replacements"=>state.cull_replacements,
        "stop_iteration"=>state.early_stop_iter,"next_rng"=>string.(rand(rng,UInt64,8)))
end
function particle_record(api)
    init=MersenneTwister(817)
    positions=randn(init,4,5);velocities=randn(init,4,5).*0.31
    pbest=randn(init,4,5);gbest=randn(init,4)
    rngs=[MersenneTwister(120+i) for i in 1:5]
    trace=Float64[]
    for i in 1:4
        api.advance_particles!(positions,velocities,pbest,gbest,fill(-2.,4),fill(2.,4),
            (w_inertia=.61+.03*i,c1=1.39,c2=1.83),rngs)
        append!(trace,vec(positions));append!(trace,vec(velocities))
    end
    Dict("positions"=>bits(positions),"velocities"=>bits(velocities),
        "history"=>bits(trace),"pbest"=>bits(pbest),"gbest"=>bits(gbest),
        "next_rng"=>[string(rand(rng,UInt64)) for rng in rngs for _ in 1:8])
end
function arithmetic_records(api)
    Dict("serial_"*mode=>serial_record(api,mode) for mode in ("regular","culling","stopping")) |>
        d->merge(d,Dict("particles"=>particle_record(api)))
end
